name: Model Documentation
  
on:
  push:
    branches:
      - main
      
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install packages
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get -yq update
        sudo apt-get -yq install graphviz doxygen
    - name: Clear docs
      run: if [ -d docs ]; then rm -rf docs; fi
    - name: Build documentation
      run: |
        cd utils/doxygen/
        bash create_docs.sh 
        mv docs/html ../../docs
    - name: Commit files
      run: |
        echo ${{ github.ref }}
        git add .
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "CI: Automated documentation build push [skip ci]" -a | exit 0
    - name: Push changes
      if: github.ref == 'refs/heads/main'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
