version: "3.5"

services:

  groimp:
    image: "ghcr.io/${CONTAINER_REG_USER}/${CONTAINER_REG_NAME}:latest"
    environment:
      GROIMP_TAG: $GROIMP_TAG
      JDK_HOME: $JDK_HOME
      GROIMP_VERSION: $GROIMP_VERSION
      GROIMP_DIR: $GROIMP_DIR
      JAVA_XMX: $JAVA_XMX
      MODEL_NAME: $MODEL_NAME
      DISPLAY: $DISPLAY
    volumes:
      - .:/var/model
      - ./ext/ext_linux:/usr/share/GroIMP/ext
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: java "-Xmx${JAVA_XMX}M" -jar "${GROIMP_DIR}/core.jar" --debug=INFO "/var/model/Scripts/${MODEL_NAME}"
    network_mode: host

  groimp_headless:
    image: "ghcr.io/${CONTAINER_REG_USER}/${CONTAINER_REG_NAME}:latest"
    environment:
      GROIMP_TAG: $GROIMP_TAG
      JDK_HOME: $JDK_HOME
      GROIMP_VERSION: $GROIMP_VERSION
      GROIMP_DIR: $GROIMP_DIR
      JAVA_XMX: $JAVA_XMX
      MODEL_NAME: $MODEL_NAME
    volumes:
      - .:/var/model
      - ./ext/ext_linux:/usr/share/GroIMP/ext
    command: java "-Xmx${JAVA_XMX}M" -jar "${GROIMP_DIR}/core.jar" --headless --debug=INFO "/var/model/Scripts/${MODEL_NAME}"

  groimp_server:
    image: "ghcr.io/${CONTAINER_REG_USER}/${CONTAINER_REG_NAME}:latest"
    environment:
      GROIMP_TAG: $GROIMP_TAG
      JDK_HOME: $JDK_HOME
      GROIMP_VERSION: $GROIMP_VERSION
      GROIMP_DIR: $GROIMP_DIR
      JAVA_XMX: $JAVA_XMX
      MODEL_NAME: $MODEL_NAME
      GROIMP_PORT: $GROIMP_PORT
    stop_grace_period: 60s
    restart: always
    ports:
      - ${GROIMP_PORT}:6666
    volumes:
      - .:/var/model
      - ./ext/ext_linux:/usr/share/GroIMP/ext
    command: java -jar "${GROIMP_DIR}/core.jar" --headless -Xserver -Xhost=0.0.0.0 -Xport=6666 "-Xmx${JAVA_XMX}M" "/var/model/Scripts/${MODEL_NAME}"
    
networks:
  default:
      name: $PROJECT_NAME
