version: "3.5"

services:

  groimp:
    image: "debian:${DEBIAN_TAG}"
    build: 
      dockerfile: services/groimp/Dockerfile
      context: .
      args:
        DEBIAN_TAG: $DEBIAN_TAG
        JDK_PKG: $JDK_PKG
        JDK_HOME: $JDK_HOME
        GROIMP_PKG: $GROIMP_PKG
        GROIMP_VERSION: $GROIMP_VERSION
        GROIMP_DIR: $GROIMP_DIR
        JAVA_XMX: $JAVA_XMX
        MODEL_NAME: $MODEL_NAME
    environment:
      DEBIAN_TAG: $DEBIAN_TAG
      JDK_PKG: $JDK_PKG
      JDK_HOME: $JDK_HOME
      GROIMP_PKG: $GROIMP_PKG
      GROIMP_VERSION: $GROIMP_VERSION
      GROIMP_DIR: $GROIMP_DIR
      JAVA_XMX: $JAVA_XMX
      MODEL_NAME: $MODEL_NAME
      DISPLAY: $DISPLAY
    volumes:
      - .:/var/model
      - ./templates/ext/ext_linux:/usr/share/GroIMP/ext
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: java "-Xmx${JAVA_XMX}M" -jar "${GROIMP_DIR}/core.jar" --debug=INFO "/var/model/src/${MODEL_NAME}"
    network_mode: host

  groimp_headless:
    image: "debian:${DEBIAN_TAG}"
    build: 
      dockerfile: services/groimp/Dockerfile
      context: .
      args:
        DEBIAN_TAG: $DEBIAN_TAG
        JDK_PKG: $JDK_PKG
        JDK_HOME: $JDK_HOME
        GROIMP_PKG: $GROIMP_PKG
        GROIMP_VERSION: $GROIMP_VERSION
        GROIMP_DIR: $GROIMP_DIR
        JAVA_XMX: $JAVA_XMX
        MODEL_NAME: $MODEL_NAME
    environment:
      DEBIAN_TAG: $DEBIAN_TAG
      JDK_PKG: $JDK_PKG
      JDK_HOME: $JDK_HOME
      GROIMP_PKG: $GROIMP_PKG
      GROIMP_VERSION: $GROIMP_VERSION
      GROIMP_DIR: $GROIMP_DIR
      JAVA_XMX: $JAVA_XMX
      MODEL_NAME: $MODEL_NAME
    depends_on:
      - groimp
    volumes:
      - .:/var/model
      - ./templates/ext/ext_linux:/usr/share/GroIMP/ext
    command: java "-Xmx${JAVA_XMX}M" -jar "${GROIMP_DIR}/core.jar" --headless --debug=INFO "/var/model/src/${MODEL_NAME}"

networks:
  default:
      name: groimp